<?php
        $comoSeConheceram['title'] = 'COMO SE CONHECERAM';
        $comoSeConheceram['text'] = 'Moravam em Brasília por anos na mesma quadra (113 da Asa Norte) e bloco, ele no primeiro andar e ela no terceiro, apesar disso, praticamente não se falavam, apenas se cumprimentavam vez ou outra. Foi por causa do Colégio Militar que finalmente se conheceram de verdade. Era o segundo ano do ensino médio(2009), quando Bianca e suas amigas tentavam cair na mesma turma, porém ela ficou em uma turma e as amigas em outra, por coincidência elas caíram na mesma turma do Rafael. O ano letivo se iniciou, Rafael e as amigas de Bianca se tornaram amigos. Como todos moravam na mesma quadra, ele, então, começou a fazer parte do “bonde” da 13 (sim, o grupo se autointitulava assim haha). A amizade demorou um pouco a fluir, devido a timidez da Bianca, mas nada que o tempo, e claro, Deus não desse seu jeitinho.<br><br> Assim, tudo começou!';

        $namoro['title'] = 'CAMINHADA PARA O NAMORO: PEDIDO DE NAMORO';
        $namoro['text1'] = 'Após alguns anos de amizade, Rafael e Bianca entram na faculdade (UnB) no mesmo período, o que os aproximou ainda mais e eles tornaram-se <b>melhores amigos</b>. Vários amigos se perguntavam: "porque eles não namoram? combinam tanto." (olha os amigos aí de novo, por isso eles têm tantos padrinhos hehe &#128514;). Em 2015, com um empurrãozinho de alguns amigos, Bianca e Rafael decidiram, pela primeira vez, conversar sobre o assunto de transformarem o relacionamento deles em algo a mais do que amizade. Tinham medo de que um possível namoro pudesse estragar o seis anos de amizade construídos até então. Nessa conversa houve um grande mal-entendido, Rafael achava que eles tinham de ir com calma pra não criarem expectativas as quais poderiam frustrar um ou outro, e com isso Bianca interpretou que ele queria que a história deles permanecesse apenas na amizade.'; 

        $namoro['text2'] = 'Ele saiu da conversa disposto a tentar aproximar-se mais dela, mas dessa vez com segundas intenções, afim de saber se dessa amizade poderia surgir um novo amor. Um dia Bianca fala pra Rafael que iria para um retiro da igreja dela, ele como já tinha traçado uma estratégia pra se aproximar mais, decidiu que iria nesse retiro, se tivesse oportunidade. Um amigo em comum dos dois, que frequentava bastante a igreja da Bianca, chamou Rafael para ir em um retiro na mesma data. Era uma oportunidade única para Rafael se aproximar mais de Bianca. Ele só esqueceu de perguntar ao amigo de qual igreja era o retiro, presumiu que os retiros eram o mesmo, por serem na mesma data, e como vocês podem imaginar, os retiros eram de igrejas diferentes&#128514&#128514. Rafael passou um final de semana inteiro no retiro "errado", não entendam mal, o retiro foi uma benção para ele, mas um dos objetivos, além de adorar a Deus, era ter a oportunidade de passar um tempo junto com a Bianca, no qual, eles poderiam se aproximar com intenções além da amizade, o que não foi possível nessa ocasião.';

        $namoro['text3'] = 'Ele continuava com a ideia de se aproximar dela, e resolveu marcar um encontro, no qual eles pudessem sair só os dois. Ele a chamou para a final de um jogo de basquete (os dois gostam muito de basquete). Ele fez questão de convidar apenas ela para o jogo. Sair sozinhos era incomum entre os amigos, pois sempre que marcavam algo incluíam todos do grupo no "rolê". Mesmo com tudo isso, Bianca estava certa de que era apenas uma saída entre dois amigos. Rafael fazia de tudo pra Bianca perceber que ele estava com segundas intenções: primeiro pagou os ingressos (o que não era nada comum entre eles), depois, no intervalo durante o jogo, pegou um dos poucos brindes que são arremessados para arquibancada e deu para ela. Nada disso foi suficiente para ela perceber que havia algo diferente, pelo contrário, acreditava que tudo que ele tinha feito foi somente pela amizade. Após o jogo, saíram para comer pizza (ela fez questão de pagar porque ele já tinha pago pelos ingressos &#128517&#128517), ela realmente não havia percebido nada. Eles se divirtiram muito e mesmo tendo sido tudo muito legal Bianca não havia demonstrado nada além de amizade por Rafael. Diante disso, ele achou que não havia interesse por parte dela e decidiu que não iria continuar insistindo, pois tinha medo de perder a linda amizade que eles haviam construído.';
          
        $namoro['text4'] = 'Depois disso a amizade deles só cresceu, continuavam muito próximos, mesmo com o grupo não se encontrando tanto quanto antes. Chegou a um ponto que eles se encontravam mais os dois sozinhos do que em grupo. Até que no final de 2016, com outro empurrãozinho dos amigos, eles decidem conversar novamente sobre o assunto de terem algo além da amizade. Dessa vez, em dezembro do mesmo ano, decidiram orar com o propósito de pedirem orientação a Deus sobre um possível namoro. Então, dois meses depois, à meia noite do dia 10 de fevereiro de 2017, um deck na asa norte... um lago... uma música (a música deles)... uma flor... uma carta... <b>um pedido...</b> uma resposta... o <b>primeiro SIM</b>. Assim eles começavam uma nova fase no relacionamento: o namoro.';

        $pedido['title'] = 'ELA DISSE COM CERTEZA';
        $pedido['text'] = 'Com poucos meses de namoro, eles já falavam sobre casamento, já sabiam que queriam passar o resto da vida um com o outro, não entendiam como demoraram tanto pra perceber que o amor da suas vidas estava tão perto. O único impedimento para casarem era a condição financeira, porém em outubro de 2018, tudo mudou, eles conseguiram um emprego fixo. Rafael, então, percebeu que não faltava mais nada e em dezembro de 2018, começou a planejar o pedido de casamento e orar a Deus acerca do assunto, sabia que tinha de ser algo muito especial, que pudesse representar o quanto a amava. Então, <b>no dia 10 de fevereiro de 2019, dia em que faziam 2 anos juntinhos de muito amor e crescimento espiritual e emocional</b>, chegou o tão sonhado pedido de casamento. Saíram para celebrar os 2 anos de namoro e finalizaram o dia com um filme no cine drive in (coincidentemente no filme, havia uma personagem chamada Bianca a qual fora pedida em casamento). Ao final do filme, Rafael inicia uma <i>live</i> no instagram, Bianca tímida e sem entender só pedia para que ele desligasse, de repente, um vídeo com o fundo do filme "A Bela e a Fera" aparecia no telão do cinema, o vídeo tinha uma declaração de Rafael e o início do pedido. Emocionada ela é vendada e levada para fora do carro. Ao retirar a venda, ela se vê cercada por amigos e familiares; balões e sparkles compunham o grande dia, e de repente ele se aproxima dela segurando em suas mãos uma rosa em redoma de vidro, réplica da do filme "A Bela e a Fera", e em meio as pétalas, a aliança, então, ele se ajoelha e faz o pedido: <b>"Quer casar comigo, meu amor?"</b>, o qual foi respondido com um: <b>"Com certeza"</b>, e assim o <b>segundo "SIM"</b> para o felizes para sempre deles foi dito.';

        $casamento['title'] = 'O GRANDE DIA';
        $casamento['text'] = 'Nosso grande dia está chegando e contamos com a presença de vocês para
          testemunhar o nosso SIM no altar, a segunda decisão mais importante de nossas vidas,
          após Cristo.';
        $casamento['text1'] = 'Celebre conosco o início da nossa união!';
        $casamento['text2'] = 'Dois serão um!';
        $casamento['text3'] = '“Um cordão de três dobras não se rompe com facilidade”';
        $casamento['text4'] = 'Eclesiastes 4:12';
      ?>  