<?php
        $comoSeConheceram['title'] = 'COMO SE CONHECERAM';
        $comoSeConheceram['text'] = 'Moravam em Brasília por anos na mesma quadra e bloco, ele no primeiro andar e ela no terceiro, apesar disso, praticamente não se falavam. Quando se cruzavam, apenas se comprimentavam com um educado: "Bom dia!", "Boa tarde!" ou "Boa noite!". Em 2009, no Colégio Militar, eles finalmente se conheceram de verdade. Era o segundo ano do ensino médio, quando Bianca e suas amigas tentavam cair na mesma turma, porém ela caiu em uma sala diferente das amigas, que por coincidência, caíram na mesma turma de Rafael. O ano letivo se iniciou e ele ficou amigo das amigas dela (confuso né hehe), amigas estas que moravam na mesma quadra deles. Assim Rafael começou a fazer parte do “bonde” da 13 (sim, o grupo se autointitulava assim haha). A amizade entre eles demorou um pouco a fluir, pois Bianca era muito tímida, mas nada que o tempo, e claro, Deus não desse seu jeitinho, e assim tudo começou.';

        $namoro['title'] = 'CAMINHADA PARA O NAMORO: PEDIDO DE NAMORO';
        $namoro['text1'] = 'Após uns aninhos de amizade, Rafa e Bia entram na faculdade (UnB) no mesmo período, o que os aproximou mais ainda e eles tornaram-se <b>melhores amigos</b>. Vários amigos  sempre se perguntavam: "porque eles não namoram? combinam tanto" (olha os amigos aí de novo, por isso eles têm tantos padrinhos hehe &#128514;). Em 2015, com um empurrãozinho de alguns amigos, Bi e Rafa decidiram, pela primeira vez, conversar sobre o assunto de transformarem o relacionamento deles em algo a mais do que amizade. Depois da conversa houve um grande mal entendido, ele falou que eles tinham que ir com calma pra não criarem expectativas que poderiam frustrar um ao outro e até acabar com a amizade que construiram ao longo de seis anos. Ela interpretou que isso queria dizer que ele não estava interessado em nada além de amizade com ela.'; 

        $namoro['text2'] = 'Ele saiu da conversa disposto a tentar se aproximar mais dela, mas dessa vez com segundas intenções, para ver se a amizade poderia se transformar em um novo amor, mas Bianca continuava achando que não havia interesse algum da parte dele e que eles seriam só amigos mesmo. Um dia ela fala pra ele que iria para um retiro da igreja em um final de semana, ele como já tinha traçado uma estratégia pra se aproximar mais, decidiu que iria nesse retiro se tivesse chance. Um amigo em comum dos dois, que frequentava bastante a igreja de Bianca, chamou Rafael para ir em um retiro no mesmo final de semana. Era uma oportunidade única, para Rafael se aproximar mais de Bianca. Porém ele esqueceu de perguntar ao amigo de qual igreja era o retiro, presumiu que os retiros eram o mesmo, só por serem na mesma data, e como vocês podem imaginar, os retiros não eram os mesmos&#128514&#128514. Rafael passou um final de semana inteiro no retiro "errado", não entendam mal, o retiro foi uma benção para ele, mas um dos objetivos, além de adorar a Deus, era ter a oportunidade de iniciar uma relação com intenções além de amizade com Bianca, o que não foi possível nessa ocasião.';

        $namoro['text3'] = 'Ele continuava com a ideia de se aproximar dela, e resolveu marcar um encontro, no qual eles pudessem sair só os dois. Ele a chamou para a final de um jogo de basquete (os dois gostavam muito de basquete). Ele fez questão de chamar apenas ela para o jogo, o que não era nada comum entre os amigos, pois sempre que alguém marcava algo incluía todos do grupo no "rolê". Ainda assim, como Bianca estava fixada na ideia de que ele não queria nada além de amizade, ela foi para o encontro achando que era apenas uma saída entre amigos. Rafael fazia de tudo pra Bianca perceber que estava com segundas intenções: pagou os ingressos (o que não era nada comum entre eles), no intervalo do jogo pegou um dos brindes que são arremessados para arquibancada e deu para ela. Nada foi suficiente para ela se abrir e perceber que tinha algo diferente, pelo contrário, achou que era tudo só na amizade mesmo. Depois do jogo saíram pra comer pizza (Bianca fez questão de pagar porque Rafael já tinha pago os ingressos &#128517&#128517), ela realmente não havia percebido nada. Esse foi um dia muito legal para os dois, mas ficou claro que Bianca achava que tinha sido tudo sem segundas intenções. Diante disso Rafael achou que não havia interesse de Bianca e decidiu que não iria continuar insistindo, tinha medo de perder a linda amizade que eles haviam construído.';
          
        $namoro['text4'] = 'Depois disso a amizade deles só crescia, continuavam muito próximos. Com o tempo o grupo não se encontrava tanto como antes, mas eles continuavam se encontrando com a mesma frequência, chegou a um ponto que se encontravam mais sozinhos do que com o grupo. Até que no final de 2016, com outro empurrãozinho de amigos, eles decidiram conversar novamente sobre o assunto de terem algo além de amizade, e dessa vez, em dezembro do mesmo ano decidiram orar com o propósito de pedirem orientação à Deus sobre um possível namoro (melhor decisão que fizeram). E então, dois meses depois, às 00:00h do dia 10 de fevereiro de 2017, um deck na asa norte, um lago, uma música (a música deles), uma flor, uma carta, um pedido veio e junto com ele o primeiro <b>SIM</b>. Assim eles começava uma nova fase no relacionamento deles: o namoro.';

        $pedido['title'] = 'ELA DISSE COM CERTEZA';
        $pedido['text'] = 'Com poucos meses de namoro, eles já falavam sobre casamento, já sabiam que queriam passar o resto da vida juntos, não entendiam como demoraram tanto tempo pra perceber que o amor de suas vidas estava tão perto. O único impedimento para casarem era a codição financeira, porém em outubro de 2018, tudo mudou, eles conseguiram um emprego fixo. Isso fez com que Rafael percebesse que não faltava mais nada. Em dezembro de 2018 ele começou a planejar o pedido, sabia que tinha que ser algo muito especial, que pudesse representar o quanto ele a amava. Então, no dia <b>10 de fevereiro de 2019, no dia em que faziam 2 anos juntinhos de muito amor e crescimento espiritual e emocional</b>, chegou o tão sonhado pedido de casamento. Saíram para celebrar os 2 anos de namoro e finalizaram o dia com um filme no cine drive in (o filme por coincidência tinha uma Bianca que era pedida em casamento), ao final do filme Rafa inicia uma live no instagram, Bi tímida e sem entender só pedia para que ele desligasse a "live", mas de repente, um vídeo com o fundo do filme "A Bela e a Fera" aparecia no telão do cinema, o vídeo tinha uma declaração de Rafael e o início do pedido. Emocionada ela é vendada e levada para fora do carro e logo descobre que está cercada de amigos e familiares, balões e sparkles compunham o grande dia, e de repente ele se ajoelha com uma aliança dentro da flor de A Bela e a Fera (sim ela ganhou uma flor igualzinha a do filme) e faz o pedido: <b>"Quer casar comigo, meu amor?"</b>, o qual foi respondido com um: <b>"Com certeza"</b>, e assim o segundo "SIM" para o felizes para sempre deles foi dito.';

        $casamento['title'] = 'O GRANDE DIA';
        $casamento['text'] = 'Nosso grande dia está chegando e contamos com a presença de vocês para
          testemunhar o nosso SIM no altar, a segunda decisão mais importante de nossas vidas,
          após Cristo.';
      ?>  